services:
  server:
    build: 
       context: ./backend
       dockerfile: Dockerfile
    image: bohdanhorlach/soundhub_pet-project-server:latest
    container_name: soundhub-server
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    restart: always
